[meta]
name = Русский
language = confessionbot_ru
flag = 🇷🇺
contributors = Freemandns, wkidish228_337
inherit = ru

[help]
introduction = - **Используйте {p:confess} в настроенном канале.** *Используйте {p:list}, чтобы просмотреть все настроенные каналы.*;
	- Администраторы могут настроить ({p:setup}) каналы и изменять настройки с помощью {p:controlpanel};
	- Модераторы могут перемешивать ({p:shuffle}) анонимные идентификаторы, проверять сообщения и блокировать ({p:block}) пользователей от отправки сообщений;
	- Используйте {p:help} (команда) для получения справки по конкретной команде.
	
	**У вас все еще есть вопросы?**
	Получите индивидуальную поддержку от разработчика и других пользователей на [сервере поддержки]({serverinv}).
bot_description = {c:main/botname} — самый продвинутый анонимный мессенджер в Discord с инструментами для модераторов, несколькими типами анонимных каналов, поддержкой изображений и многим другим!
	Для начала настройте ({p:setup}) анонимный канал.
about_field1_title = ✨ Анонимность+
about_field1_value = **Наслаждайтесь анонимным общением, не отказываясь от модерации.** Модераторы могут блокировать пользователей по их анонимным идентификаторам или сразу менять местами все анонимные идентификаторы на сервере. Каналы обратной связи также можно использовать для анонимного информирования о нарушениях.
about_field2_title = 🔧 Типы каналов для каждого сервера
about_field2_value = **Для каждого есть свой тип канала!** Анонимные идентификаторы можно показывать или скрывать в каждом канале, можно включить проверку на уровне всего сервера, чтобы все сообщения публиковались только после одобрения, а в каналах обратной связи можно отправлять сообщения, не видя других.
about_field3_title = 🖼 Поддержка изображений
about_field3_value = **Изображения по умолчанию автоматически отправляются вместе с анонимными сообщениями.** Это довольно редкое явление для ботов для отправки анонимных сообщений. При желании администраторы могут отключить эту функцию в {p:controlpanel}.
about_field4_title = 🌍 Поддержка перевода
about_field4_value = **{c:main/botname} говорит на нескольких языках и может быть переведен на другие при поддержке сообщества.** Проверьте {p:language list}, чтобы узнать, какие переводы доступны на данный момент.
about_field5_title = 💵 Еще больше возможностей благодаря премиум
about_field5_value = **Поддержите разработку и получите приятные эстетические бонусы для своего сервера!** Узнайте больше о премиальных бонусах с помощью {p:premium}.

[premium]
feature_1 = Компактный режим
feature_1_desc = **Наслаждайтесь анонимными сообщениями в новом компактном формате!** - При включенном компактном формате анонимных сообщений у каждого участника вашего сервера будет анонимный идентификатор и аватарка, поэтому для сообщений не потребуется столько места. *Включите эту функцию в {p:controlpanel}*.
feature_2 = Персонализируйте {c:main/botname} на своем сервере
feature_2_desc = **Добавьте фирменное сообщение над каждым анонимным сообщением** - Вы можете указать роль или наименование своего сервера. *Включите это в {p:controlpanel}*.

	**Переименуйте /confess** — измените название команды {p:confess}, чтобы тесно интегрировать {c:main/botname} в свой сервер. *Включите эту функцию в {p:controlpanel}*.
feature_custom_desc = **Доступны личные сообщения и пользовательские функции** - Свяжитесь с {c:main/creator} на сервере поддержки [{c:help/serverinv}] по поводу ваших пользовательских требований. *Для этого требуется более дорогостоящий уровень поддержки*.

[confessions]
command_Confession_Reply = Ответить анонимным сообщением
command_Confession_Report = Отчет об анонимном сообщение
command_confess = confess
command_confess_desc = Отправьте анонимное сообщение на этот канал.
command_confess_content_desc = Текст вашего анонимного сообщения, оставьте пустым для редактирования абзацев.
command_confess_image_desc = Необязательное изображение, которое может отображаться под текстом или вместо него.
command_confess_help = {p:{cmd}} [сообщение] [изображение]
	Напишите анонимное сообщение для отправки в этом канале. Работает, только если канал настроен. {p:confess} без дополнительных параметров откроет редактор абзацев.
	Поддерживаются только изображения. Видео (и любые другие файлы) не отправляются.
command_confess-to = confess-to
command_confess-to_desc = Отправьте анонимное сообщение в определенный канал.
command_confess-to_channel_desc = Канал, на который вы хотите отправить сообщение. В том числе каналы, которые вы не видите.
command_confess-to_help = {p:{cmd}} (канал) [сообщение] [изображение]
	Напишите анонимное сообщение для отправки в любой канал на этом сервере. Автозаполнение предложит список всех доступных каналов.
	О том, как написать анонимное сообщение, читайте в разделе "{p:help} confess".
command_setup = setup
command_setup_desc = Управление анонимными каналами и их настройками
command_setup_help = {p:{cmd}}
	Открывает интерактивную панель, на которой вы можете настроить каналы confessions и изменить настройки для каждого канала.
command_list = list
command_list_desc = Перечислить все анонимные каналы, доступные здесь.
command_list_help = {p:{cmd}}
	Список всех доступных на данный момент анонимных каналов на этом сервере.
command_block = block
command_block_desc = Блокируйте или разблокируйте любой указанный анонимный идентификатор на этом сервере.
command_block_anonid_desc = Идентификатор Anon-ID рядом с отслеживаемым анонимным сообщением
command_block_unblock_desc = Разблокирует Anon-ID, если для этого параметра установлено значение true
command_block_help = {p:{cmd}} (anon-id) [unblock]
	Запретите любому пользователю с анонимным идентификатором отправлять анонимные сообщения. Запрет будет действовать до тех пор, пока вы не поменяете идентификаторы.
	Чтобы разблокировать, установите для параметра unblock значение true. Например. {p:block} anonid=abc123 unblock=true
command_shuffle = shuffle
command_shuffle_desc = Для защиты анонимности все анонимные идентификаторы на этом сервере будут перемешаны случайным образом
command_shuffle_help = {p:{cmd}}
	Обнуляет все анонимные идентификаторы, чтобы снизить вероятность отслеживания и идентификации одного пользователя.
command_sell = sell
command_sell_desc = Укажите товар, который вы хотите продать анонимно
command_sell_title_desc = Опишите, что вы продаете, в нескольких словах
command_sell_starting_price_desc = Целевая цена, которую вы, скорее всего, согласитесь принять, указана в валюте
command_sell_payment_methods_desc = Укажите способы оплаты, которые вы принимаете. Например, PayPal, Venmo, криптовалюта
command_sell_description_desc = Подробно опишите, что вы продаете, и используйте /confess, чтобы добавить информацию позже
command_sell_image_desc = Изображение товара, если применимо
command_sell_help = {p:{cmd}} (title) (starting_price) (payment_methods) [description] [image]
	Создайте объявление о продаже товара. Объявления можно размещать только на каналах maretplace — используйте {p:list}, чтобы найти подходящий.
	Объявления анонимны, но после того, как вы примете ценовое предложение от покупателя, вы обменяетесь именами пользователей.
	Заголовок должен быть коротким.
	Начальная цена должна быть указана в валюте, например в долларах США, канадских долларах, евро или иенах.
	Способы оплаты могут быть любыми: банковские переводы, криптовалюта или платформа вроде Paypal.
; keywords
channeltype_-1 = Не установленный
channeltype_0-1 = Анонимный
channeltype_2 = Проверка
channeltype_3-4 = Обратная связь
channeltype_5 = Рыночная площадь
channeltype_traceable = (АнонИДы)
channeltype_untraceable = (Не поддающийся отслеживанию)
; controlpanel labels
dm_notifications = Отключить уведомления от ЛС
guild_banlist = Запрещенные идентификаторы анонимов
image_support = Поддержка изображений
enable_webhooks = Компактные анонимные сообщения
confession_preface = Маркировка анонимных сообщений
confess_custom_name = Пользовательская команда /confess
; errors
inaccessible = У вас нет доступа к анонимным каналам.
    *Для запуска администратору необходимо {p:setup} канал.*
inaccessiblelocal = На этом сервере нет анонимных каналов.
    *Для запуска администратору необходимо {p:setup} канал.*
invalidanonid = Указанный вами анонимный идентификатор недействителен!
doublebananonid = Этот анонимный аккаунт уже был забанен!
nomatchanonid = Я не смог найти этот анонимный идентификатор.
missingperms = Отправить анонимное сообщение не удалось, так как мне требуется разрешение {perm} в целевом канале.
embederr = Не удалось отправить сообщение! Скорее всего, у меня нет разрешения на отправку встроенных сообщений.
missingchannelerr = Не удается отправить сообщения в этот канал. Возможно, он больше не существует или я потерял к нему доступ.
timeouterror = Срок действия этого ввода истек.
singlechannel = Эту настройку можно задать только для одного канала на сервере.
no_change = Режим тот же, так что ничего не изменилось.
nospam = Это сообщение было автоматически заблокировано как спам.
vettingrequiredmissing = Не удалось отправить одобренное сообщение. Вероятно, у меня нет прав `VIEW_CHANNEL` для целевого канала.
dmconfessiondisabled = Из соображений производительности функция «Анониманые сообщения в личных сообщениях» и {p:list} в личных сообщениях были отключены. Вместо них используйте {p:confess}, {p:confess-to} и {p:list} на предпочитаемом вами сервере.
	https://media.discordapp.net/attachments/808905578947674112/973161489487781908/GIF.gif
no_moderation = В этом боте отключены функции модерации, поэтому сейчас это невозможно.
; warnings
cachebuilding = {c:main/botname} все еще запускается, поэтому списки каналов в личных сообщениях могут быть неполными.
	> *{p:confess}, {p:confess-to} и {p:list} работают без задержек на серверах.*
vetting = **На некоторых из этих каналов включена функция проверки.** Модератору сервера может потребоваться подтвердить или отклонить ваше анонимное сообщение, прежде чем оно будет опубликовано. При этом вы сохраните анонимность на протяжении всего процесса.
concat_list = Этот список неполный, используйте /list, чтобы увидеть все
; confessions
channelprompt = Выберите канал назначения для анонимного сообщения.
channelprompt_pager = Страница {page}
channelprompt_placeholder = Целевой канал
channelprompted = Ваше анонимное сообщение будет отправлено в {channel}.
	{vetting?*Здесь включена проверка. Ваше сообщение должно быть одобрено модераторами, прежде чем оно станет общедоступным.*|}
channelprompt_button_send = Отправить сообщение
channelprompt_button_sent = Отправленное сообщение
channelprompt_button_prev = Предыдущая страница
channelprompt_button_next = Следующая страница
editor_title = Редактор анонимных сообщений
editor_message_label = Сообщение:
editor_message_placeholder = Текст, который станет вашим анонимным сообщением
confession_reply_failed = Невозможно ответить на сообщения такого типа. Попробуйте ответить на другое сообщение.
confession_sent_channel = Готово, ваше сообщение отправлено в {channel}.
confession_sent_below = Готово, ваше сообщение ниже.
confession_vetting = Ваше сообщение будет проверено и, если его одобрят, появится в {channel}.
confession_vetting_denied = Ваше сообщение не прошло проверку.
confession_vetting_accepted = Ваше сообщение принято и опубликовано в {channel}.
nosendchannel = Здесь нельзя отправлять анонимные сообщения! Используйте эту команду в канале из {p:list}.
nosendbanned = Ничего не выйдет, вас забанили на этом сервере.
nosendimages = Ничего не выйдет, на этом сервере отключены анонимные изображения.
invalidimage = Похоже, это не настоящий файл с изображением.
wrongcommand = Вы должны использовать команду {p:{cmd}} в {channel}.
reply_to = Ответ на {reference};
; setup
setup_start = Ниже представлена текущая конфигурация этого канала. Отсюда вы можете настроить любой канал.
	*Нажмите на кнопку «Справка» ниже, чтобы узнать больше о том, как работает этот канал.*
setup_placeholder = Целевой канал
setup_state = Канал {channel} в настоящее время находится в состоянии `{state}`.
setup_state_missing = Не удалось получить доступ к этому каналу.
state_desc_-1 = > **Неподписанные каналы** не будут принимать анонимные сообщения. Однако вы по-прежнему можете использовать другие команды бота.
state_desc_0 = > **Анонимные (не отслеживаемые) каналы** скрывают анонимные идентификаторы для обеспечения дополнительной анонимности, однако, если установлен канал проверки, анонимные идентификаторы все равно будут отображаться в нем.
state_desc_1 = > **Анонимные каналы (Anon-IDs)** используются по умолчанию. Рядом с сообщениями отображаются Anon-IDs (случайные коды на основе вашего идентификатора пользователя). По ним нельзя найти пользователей, но у каждого пользователя свой цвет и идентификатор.
state_desc_2 = > **Канал проверки** перехватывает анонимные сообщения до того, как они становятся общедоступными. Модераторы могут одобрять или отклонять анонимное сообщение. Отзывы не проверяются.
state_desc_3 = > **Каналы обратной связи (анонимные идентификаторы)** доступны всем пользователям вашего сервера, даже если они не видят сам канал. Пользователям нужно просто использовать {p:confess-to} вместо других способов.
state_desc_4 = > **Каналы обратной связи (не отслеживаемые) ** могут использоваться всеми участниками сервера без необходимости их просмотра, а также не содержат идентификаторов анонимных пользователей. Для использования этого канала пользователям может потребоваться использовать {p:confess-to}.
state_desc_5 = > **Каналы маркетплейса** работают по тому же принципу, что и анонимные каналы (AnonIDs), но анонимные сообщения предназначены для использования в качестве объявлений на маркетплейсе. Пользователи могут делать предложения и договариваться о цене, после чего их имена становятся известны.
state_cta = *Чтобы изменить это поведение, выберите новый тип канала ниже.*
setup_controlpanel = Используйте /controlpanel для настройки всего сервера
setup_help = Помощь
setup_anonids = AnonIDs: {anonids?Показанный|Скрытый}
setsuccess0 = Теперь в этом канале будут публиковаться анонимные сообщения без указания личных данных!
setsuccess1 = Теперь в этом канале будут анонимные сообщения с идентификаторами!
setsuccess2 = Этот канал теперь будет использоваться для проверки сообщений.
	*Убедитесь, что доступ к этому каналу есть только у модераторов!*
setsuccess3 = Теперь в этом канале будет публиковаться анонимная обратная связь с идентификаторами!
	*Убедитесь, что доступ к этому каналу есть только у модераторов!*
setsuccess4 = Теперь в этом канале будет публиковаться анонимная обратная связь без указания личных данных!
	*Убедитесь, что доступ к этому каналу есть только у модераторов!*
setsuccess5 = Теперь этот канал будет функционировать как анонимная торговая площадка.
setcta = Чтобы начать, используйте {p:{cmd1}} в этом канале!{cmd2? (*Если вы не можете печатать здесь, используйте {p:{cmd2}} в другом канале.*)|}
setundo = Чтобы отменить это действие, установите для типа канала значение `Unset` в {p:setup}.
; unsetting
unsetsuccess0 = Этот канал больше не будет принимать анонимные сообщения!
unsetsuccess1 = Этот канал больше не будет принимать анонимные сообщения!
unsetsuccess2 = Этот канал больше не будет использоваться для проверки сообщений.
unsetsuccess3 = Этот канал больше не будет использоваться для анонимной обратной связи.
unsetsuccess4 = Этот канал больше не будет использоваться для анонимной обратной связи.
unsetsuccess5 = На этом канале больше не будет анонимной торговой площадки.
unsetundo = Но убедитесь, что хотя бы один канал настроен!
unsetfailure = Этот канал не установлен, поэтому его нельзя отменить.
; list
listtitle = Вы можете отправлять анонимные сообщения на эти каналы:
listtitlelocal = На этом сервере вы можете отправлять анонимные сообщения в следующие каналы:
confess_to_feedback = **Если вы не видите канал «Обратная связь» (📢):** отправьте анонимное сообщение через {p:confess-to}.
; report
report_prep = ## Отчет {msgurl}
	**Пожалуйста, прочтите [{c:main/botname} Условия использования]({c:main/tos_url}) перед продолжением!**
	Еще кое-что, что вам следует знать;
	- Сообщения отправляются непосредственно разработчикам бота. Если они сочтут, что это сообщение нарушает правила, они могут заблокировать пользователя в этом боте.
	- Если будет установлено, что сервер в целом нарушает Условия использования этого бота, весь сервер может быть заблокирован для использования этого бота.
	- If this is a minor transgression, you should talk to moderators and admins on this server.
	Если вы считаете, что в этом сообщении есть что-то, нарушающее {c:main/botname} Условия предоставления услуг, нажмите кнопку ниже, чтобы продолжить.
report_button = Продолжать сообщать
report_title = Сообщить об анонимном сообщение
report_field = Причина сообщения
report_placeholder = Обоснование вашего мнения о том, что это противоречит Условиям использования {c:main/botname}
report_invalid_message = Сообщение, о котором вы хотите сообщить, не похожее на анонимное сообщение!
report_failed = К сожалению, отправить ваш отчет не удалось! Пожалуйста, сделайте скриншоты и отправьте их {c:help/serverinv} или в личные сообщения {c:main/creator} (владельцу бота).
report_success = Ваш отчет успешно отправлен! Чтобы узнать статус вашего отчета, [подпишитесь на сервер поддержки]({c:help/serverinv}).
new_report = {server} получил следующее анонимное сообщение от {user} по следующей причине:
	> {reason}
; ban
bansuccess = Анонимус-{user} заблокирован.
	Чтобы разблокировать их, используйте {p:block}` anonid:{user} unblock:true` или {p:shuffle} идентификаторы.
unbansuccess = {user} разблокирован.
banlist = Вот список заблокированных в настоящее время анонимных идентификаторов;
emptybanlist = На этом сервере в данный момент никто не заблокирован!
; shuffle
; this 'yes' must remain a 'yes' in translation.
shufflebanresetwarning = При перетасовке все активные запреты будут сброшены. Вы хотите продолжить?
shufflebanresetconfirm = Продолжать
shufflesuccess = Все анонимные идентификаторы на этом сервере перемешаны!
; vetting
vetmessagecta = Ожидающее обработки сообщение для {channel}.
vetcorrupt = Из-за обновлений безопасности это ожидающее подтверждения сообщение устарело, проверка больше невозможна.
vetaccepted = Это анонимное сообщение было принято {user} и отправлено в {channel}.
vetdenied = Это анонимное сообщение было отклонено {user}, оно было направлено в {channel}.
vetting_approve_button = Одобрить
vetting_deny_button = Отрицать
vet_error_module = Это сообщение не может быть отправлено без {module}, который в данный момент недоступен.
; marketplace
shop_disclaimer = {c:main/botname} не может гарантировать успешное проведение транзакций. Имена пользователей передаются в частном порядке после того, как продавец принимает предложение.
button_offer = Сделать предложение{listing? ({listing})|}
button_accept = Принять предложение ({listing?{listing}|только для продавца})
button_withdraw = Вывести {sell?перечисление|предложение} ({sell?продавец|покупатель} только)
offer_price_label = Сумма предложения (с валютой):
offer_price_example = US$30
offer_method_label = Способ оплаты:
offer_method_example = PayPal, Крипто, Банковский перевод
error_embed_deleted = Информация о листинге удалена — невозможно сделать предложение.
error_self_offer = Вы не можете сделать предложение самому себе.
error_wrong_person = Только создатель этого {buy?листинга|предложения} может выполнить это действие.
sale_complete = # {listing} продано
	Поздравляем, {sell?ваш товар был продан|вы согласились купить товар у} {other}. Свяжитесь с ними, чтобы договориться об оплате и доставке.
	Для вашего сведения, объявление и предложение прикреплены ниже. {sell? Если у вас больше нет этого товара на продажу, удалите объявление с сервера.|}
offer_for = Предложение для "{listing}"
listing_withdrawn = Это объявление было удалено
offer_withdrawn = Это предложение было отозвано
offer_accepted = Это предложение было принято продавцом
